Revert "Removed everything, ZOMG! (This is part of a hack to get a PR…
apostrophecms/apostrophe-external-notifications pull request #1
Opened 2019-07-09 15:35 UTC by boutell

… of the whole thing)"

This reverts commit fdb2c8292b11322c98819c8c29b70ca8f0de031d.

2019-07-09 19:08 UTC, abea commented on index.js
> +        if (!options) {
This could be checked prior to the loop to avoid duplicative checking.

2019-07-09 19:12 UTC, abea commented on index.js
> +        '{user} committed the {type} {title} in {string}', commit.from, commit.from, liveify(commit.from.workflowLocale)
Grammar point: `{title}` should be separated by commas. So `'{user} committed the {type}, {title}, in {string}'`. Same for the next two.

On a related note, I just learned this is called an apposition. https://www.grammarly.com/blog/appositive/

2019-07-09 19:15 UTC, abea commented on package.json
> +    "content",
I don't think we should include the pieces of CMS as individual keywords as they're too general on their own.

2019-07-09 19:28 UTC, abea commented on index.js
> +        const formatted = self.format(req, formatArgs[0], ...formatArgs.slice(1));
I'm confused by this piece. It seems like the first two arguments are `req` if req is the first argument from the start. Then couldn't the arguments just be after req simply be `(req, ...formatArgs)` rather than passing in the first before the rest with the first sliced off?

2019-07-09 19:29 UTC, abea commented on index.js
> +        const formatted = self.format(req, formatArgs[0], ...formatArgs.slice(1));
Was the `req` argument supposed to be removed after declaring that constant?

2019-07-09 19:47 UTC, abea commented on index.js
> +        '{user} committed the {type} {title} in {string}', commit.from, commit.from, liveify(commit.from.workflowLocale)
@boutell Can you point me to where these events are emitted to help review this?

2019-07-09 21:18 UTC, abea requested changes
Two really minor things. This is really cool!

2019-07-09 21:18 UTC, abea commented on index.js
> +        if (!options) {
This could be checked prior to the loop to avoid duplicative checking.

2019-07-09 21:18 UTC, abea commented on package.json
> +    "content",
I don't think we should include the pieces of CMS as individual keywords as they're too general on their own.

2019-07-10 12:45 UTC, boutell commented on index.js
> +        if (!options) {
I'm going to leave this one as is because it is slightly more tolerant not to fail unless channels are really configured for slack.

2019-07-10 12:46 UTC, boutell commented on index.js
> +        if (!options) {
(And it'll fail on the first one, so there's no real overhead.)

2019-07-10 13:23 UTC, merged